### ISSUE TITLE
无法使用在新版Redmine 2.6.1

### ISSUE THREAD

**Issue by wildpeanut** [wenzhixin/redmine-chrome#36]
估计有可能是外挂造成，以下列出已安装的外挂

Clipboard image paste 	1.9
Redmine Agile plugin (Light version) 	1.3.5
Redmine Code Review plugin 	0.6.4
DMSFDocument Management System 	1.4.9 stable
Redmine Graphs plugin	0.1.0
Redmine Hudson plugin 	2.1.2
Project Search Box Plugin 	0.0.3
Redmine Light Box plugin 	0.0.1
Redmine (Monitoring & Controlling | Monitoramento & Controle) 	0.1.1
Mylyn Connector plugin	2.8.2.stable
Redmine Requirements Engineering Plugin 	development version
Redmine Theme Changer plugin 	0.1.0
Sidebar Hide Plugin 	0.0.7

**Comment by wenzhixin** [comment]
v 2.3.0 应该可以了。

**Comment by wildpeanut** [comment]
感谢
