### ISSUE TITLE
Create Tool bar for comments

### ISSUE THREAD

**Issue by ToniGithub** [wenzhixin/redmine-chrome#40]
Perfect Extension but I need a Tool bar for select format settings like create a link or bold, italic, emphasis format text, etc...

**Comment by wenzhixin** [comment]
> create a link or bold, italic, emphasis format text, etc...

Do you mean adding these feature to the comment textare?

**Comment by ToniGithub** [comment]
Exactly. I don't remember the special characters for text formatting... A tool bar help me for this.

Thank you in advance!

**Comment by wenzhixin** [comment]
Consider to add this feature.

**Comment by ToniGithub** [comment]
Thank you Wenzhixin. 

I have more new features to add in your extension (like create new issues directly or adding a text filter and project classification) but it is more complex... I think.
