### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by YADeM** [wenzhixin/redmine-chrome#45]
suggest to add russian localization
[ru-RU.zip](https://github.com/wenzhixin/redmine-chrome/files/142214/ru-RU.zip)

**Comment by wenzhixin** [comment]
Can you help to create a Pull request?
https://github.com/wenzhixin/redmine-chrome/tree/master/locale

**Comment by YADeM** [comment]
it's new for me, but i try to add.

**Comment by wenzhixin** [comment]
:+1:

**Comment by YADeM** [comment]
Can you update with russian version chrome store?

**Comment by wenzhixin** [comment]
OK, I will release a new version as soon as possible.

**Comment by YADeM** [comment]
Thank you very much. Some of my colleagues waiting for official russian version )))

**Comment by wenzhixin** [comment]
Released
