### ISSUE TITLE
Issue status - get from server

### ISSUE THREAD

**Issue by YADeM** [wenzhixin/redmine-chrome#51]
I thins that is good idea - to get issue statuses from redmine server.

**Comment by wenzhixin** [comment]
What do you mean?

**Comment by YADeM** [comment]
Sorry write not clearly.
Better to add issues status from  server in Settings.

**Comment by wenzhixin** [comment]
![image](https://cloud.githubusercontent.com/assets/2117018/13454425/fdf13a2c-e091-11e5-8102-10148da270e4.png)
Here?

**Comment by YADeM** [comment]
yes, because at my server we have different issues statuses
